<html>
<head>
    <meta charset="utf-8" />
    <title><?=$title?></title>
</head>
<body>
    <h1><?=$title?></h1>
        <div id="iagaChart">
        <?php if (isset($error)) {
        	echo $error;
        }?>
        </div>
    <?php if (!isset($error)):?>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script>
        var iaga = {
//                 parseSerie: function (options) {
//                 	   options.tooltip.formatter = iaga.formatterDefault;
//                        options.series.forEach(function(serie) {
//                            serie.data.forEach(function(line, key) {
//                                serie.data[key][0] = Date.parse(serie.data[key][0]);
//                            })
//                        })
//                        console.log(options.series);
//                        return options;
//                 },
                val2kp: function (val) {
                    
                },
                formatterDefault: function () {
                    var s =  Highcharts.dateFormat('%e %b %Y %H:%M', this.x) ;

                    this.points.forEach(function(point, i) {
                        if( point.series.name != 'hidden'){
                            s += '<br/><span style="color:'+ point.series.color +';">\u25AC</span> '+ point.series.name +': ' ;
                        }
                        if (point.series.type =='column') {
                            //Kp values
                            if ((point.y - Math.floor(point.y))==0) { s+= Math.floor(point.y) +'o'; }
                            if (((point.y - Math.floor(point.y))>0) && ((point.y - Math.floor(point.y))<0.4)) { s+= Math.floor(point.y) +'+'; }
                            if ((point.y - Math.floor(point.y))>0.6) { s+= Math.round(point.y) +'-'; }
                        } else {
                            s += point.y ;
                        }
                    });
           
                    return s;
                },
                formatterQdays: function() {
                    var s =  Highcharts.dateFormat('%e %b %Y', this.x) ;
                    this.points.forEach(function(point, i) {
                   	     if(point.y>0){
                            s += '<br/><span style="color:'+ point.series.color +'">\u25AC</span> '+ point.series.name  ;
                   	     }
                    });
                    return s;
       	         }
        }
       var options = <?=json_encode($options, JSON_NUMERIC_CHECK)?>;
       options.tooltip.formatter = iaga[options.tooltip.formatter];
       console.log(options.yAxis);
     //  options = iaga.parseSerie(options);
        Highcharts.chart('iagaChart', options);
    </script>
    <?php endif;?>
</body>    
</html>