<?php var_dump($options);?>
<html>
<head>
    <meta charset="utf-8" />
    <title><?=$title?></title>
</head>
<body>
    <h1><?=$title?></h1>
        <div id="iagaChart">
        <?php if (isset($error)) {
        	echo $error;
        }?>
        </div>
    <?php if (!isset($error)):?>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script>
        Highcharts.chart('iagaChart', <?=json_encode($options, JSON_NUMERIC_CHECK)?>);
    </script>
    <?php endif;?>
</body>    
</html>